[package]
name = "pace_starter"
version = "0.0.1"
edition = "2021"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[dependencies]
nersent_pace = "0.1.0"
chrono = "0.4.23"
polars = { version = "0.27.2", features = ["parquet", "lazy"] }
